### ISSUE TITLE
Eat raw villager on kebab skewer

### ISSUE THREAD

**Issue by AlBuSoft** [FartSolutions/InsanityCraft#2]
# Description
Change the name of the kebab skewer with villager to `kebab_skewer_raw_villager` and implements that you can eat this item and get `2` hunger and change the item `kebab_skewer_raw_villager` to empty `kebab_skewer`.

# Tasks
- [ ] Rename `kebab_skewer_villager` to `kebab_skewer_raw_villager`
- [ ] Implement the eat feature (2 hunger)
- [ ] Change after eat to empty `kebab_skewer`
